In [0]:
import nltk 

In [0]:
import spacy
nlp = spacy.load("en") 

In [0]:
william_wikidef = """William was the son of King William
II and Anna Pavlovna of Russia. On the abdication of his
grandfather William I in 1840, he became the Prince of Orange.
On the death of his father in 1849, he succeeded as king of the
Netherlands. William married his cousin Sophie of Württemberg
in 1839 and they had three sons, William, Maurice, and
Alexander, all of whom predeceased him. """
nlp_william = nlp(william_wikidef)
print([ (i, i.label_, i.label) for i in nlp_william.ents])

[(William, 'PERSON', 380), (King William, 'PERSON', 380), (Anna Pavlovna, 'PERSON', 380), (Russia, 'GPE', 384), (grandfather William I, 'PERSON', 380), (1840, 'DATE', 391), (the Prince of Orange, 'LOC', 385), (1849, 'DATE', 391), (the
Netherlands, 'GPE', 384), (William, 'PERSON', 380), (Sophie, 'PERSON', 380), (Württemberg, 'PERSON', 380), (1839, 'DATE', 391), (three, 'CARDINAL', 397), (William, 'PERSON', 380), (Maurice, 'PERSON', 380), (Alexander, 'PERSON', 380)]


In [0]:
from textblob import TextBlob
from textblob.classifiers import NaiveBayesClassifier
data = [
('I love my country.', 'pos'),
('This is an amazing place!', 'pos'),
('I do not like the smell of this place.', 'neg'),
('I do not like this restaurant', 'neg'),
('I am tired of hearing your nonsense.', 'neg'),
("I always aspire to be like him", 'pos'),
("It's a horrible performance.", "neg")
]

In [0]:
model = NaiveBayesClassifier(data)
model.classify("I am very happy today man")

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
texts=["Ramiess sings classic songs","he listens to old pop",
"and rock music", ' and also listens to classical songs']
vect = TfidfVectorizer()
X = vect.fit_transform(texts)
print(X.todense())

[[0.         0.         0.52547275 0.         0.         0.
  0.         0.         0.         0.52547275 0.         0.52547275
  0.41428875 0.        ]
 [0.         0.         0.         0.         0.48546061 0.38274272
  0.         0.48546061 0.48546061 0.         0.         0.
  0.         0.38274272]
 [0.         0.48693426 0.         0.         0.         0.
  0.61761437 0.         0.         0.         0.61761437 0.
  0.         0.        ]
 [0.47212003 0.37222485 0.         0.47212003 0.         0.37222485
  0.         0.         0.         0.         0.         0.
  0.37222485 0.37222485]]


In [0]:
1+1


2

In [0]:
import tensorflow as tf

In [0]:
hello = tf.constant('Hello Tensors!')

In [0]:
sess = tf.sess()

In [0]:
import keras 
from keras.layers import Dense
from keras.models import Sequential
import numpy as np


In [0]:
mlp_keras = Sequential()
mlp_keras.add(Dense(8, input_dim=4, init='uniform',activation='relu'))
mlp_keras.add(Dense(6, init='uniform', activation='relu'))

In [0]:
mlp_keras.add(Dense(1, init='uniform', activation='sigmoid'))

In [17]:
from tensorflow import keras


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?'
]

tokenizer = Tokenizer(num_words = 100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequences, maxlen=5)
print("\nWord Index = " , word_index)
print("\nSequences = " , sequences)
print("\nPadded Sequences:")
print(padded)


# Try with words that the tokenizer wasn't fit to
test_data = [
    'i really love my dog',
    'my dog loves my manatee'
]

test_seq = tokenizer.texts_to_sequences(test_data)
print("\nTest Sequence = ", test_seq)

padded = pad_sequences(test_seq, maxlen=10, padding='post')
print("\nPadded Test Sequence: ")
print(padded)


Word Index =  {'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}

Sequences =  [[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]

Padded Sequences:
[[ 0  5  3  2  4]
 [ 0  5  3  2  7]
 [ 0  6  3  2  4]
 [ 9  2  4 10 11]]

Test Sequence =  [[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]

Padded Test Sequence: 
[[5 1 3 2 4 0 0 0 0 0]
 [2 4 1 2 1 0 0 0 0 0]]


In [0]:
ocab_size = 10000
embedding_dim = 16
max_length = 100
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"
training_size = 20000
